version: '3.8'

services:
  db:
    image: postgres:16.2
    container_name: my_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
